# Generated by Django 3.0 on 2020-12-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('number_two', models.IntegerField(blank=True, null=True)),
                ('Email', models.CharField(max_length=100)),
                ('label', models.CharField(choices=[('M', 'Morning'), ('N', 'Noon'), ('AN', 'AfterNoon')], max_length=2)),
                ('times', models.DateTimeField()),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
            ],
        ),
    ]
