# Generated by Django 3.0 on 2020-12-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gets',
            name='times',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
