# Generated by Django 3.0 on 2020-12-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201208_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gets',
            name='slug',
        ),
        migrations.AlterField(
            model_name='gets',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
